package org.uche.t0ken.commons.enums;

public enum ParameterName {
	
	
	/*
	 * GDAX
	 */
	
	STRING_REST_ENDPOINT,
	STRING_WEBSOCKET_FEED,
	LONG_WEBSOCKET_CONNECT_ERROR_SLEEP_MILLIS,
	LONG_WEBSOCKET_CONNECTED_SLEEP_MILLIS,
	STRING_GDAX_PRODUCTS,
	STRING_GDAX_FEES,
	INTEGER_GDAX_API_MAX_CONCURRENT_REQUESTS,
	INTEGER_GDAX_CLIENT_DESPOOL_QUEUE_SIZE,
	INTEGER_GDAX_CLIENT_DESPOOL_CONSUMERS,
	LONG_GDAX_CANCEL_ORDER_TIMEOUT,
	LONG_GDAX_NEW_ORDER_TIMEOUT,
	
	
	/*
	 * FAKE
	 * 
	 */
	
	STRING_FAKE_FEES,
	/*
	 * Refresh
	 */
	LONG_PARAMETER_REFRESH_MILLIS,
	
	/*
	 * DEFAULT PARAMS
	 */
	STRING_NODE_TIMEZONE,
	INTEGER_DATA_GRANULARITY,
	INTEGER_USE_DG_UNTIL_SG,
	INTEGER_DEFAULT_ACCOUNT_SCALE,
	/*
	
	/*
	 * TRADING
	 */
	
	DOUBLE_PAT1_MIN_DIST_FROM_EMAC_12,
	DOUBLE_PAT1_MIN_MACDCD_1226_P,
	
	/*
	 * DEBUG
	 */
	BOOLEAN_DEBUG_PARAMETER_CACHE_MANAGER,
	BOOLEAN_DEBUG_STAT_CACHE_MANAGER,
	BOOLEAN_DEBUG_CLIENT_SERVICE,
	BOOLEAN_DEBUG_STAT_SERVICE,
	BOOLEAN_DEBUG_API_STATS,
	BOOLEAN_DEBUG_WEBSOCKET_SERVICE,
	BOOLEAN_DEBUG_TRADING_SERVICE,
	STRING_DEBUG_BOT_TRADER_ID_LIST,
	BOOLEAN_DEBUG_DUMMY_TRADING_SERVICE,
	BOOLEAN_DEBUG_GDAX_CLIENT_CONTROLLER,
	BOOLEAN_DEBUG_GDAX_CLIENT_SERVICE,
	BOOLEAN_DEBUG_DUMP_GDAX_QUEUES,
	BOOLEAN_DEBUG_FAKE_MARKETPLACE_SERVICE,
	/*
	 * DUMP
	 */
	BOOLEAN_DUMP_ORDER_BOOKS,
	BOOLEAN_DUMP_MATCHES,
	BOOLEAN_DUMP_PRODUCT_STAT_MEM,
	BOOLEAN_DUMP_PRODUCT_STAT_INDICATORS,
	BOOLEAN_DUMP_PRODUCT_STAT_FLUSH,
	BOOLEAN_DUMP_BOT_FLUSH,
	BOOLEAN_DUMP_BOT_MANAGEMENT,
	
	/*
	 * Permission
	 */
	STRING_API_ADMINISTRATIVE_ALLOWED_IP_ADDRESSES,
	STRING_API_UI_ALLOWED_IP_ADDRESSES,
	
	/*
	 * Rest Client
	 */
	INTEGER_CLIENT_DESPOOL_MAX_PER_ITERATION,
	LONG_CLIENT_SLEEP_PER_ITERATION_MILLIS,
	INTEGER_CLIENT_DESPOOL_MAX_TRIES,
	
	
	/*
	 * Stats
	 */
	LONG_STAT_SLEEP_PER_FLUSH_MILLIS,
	STRING_STAT_TS_FORMAT,
	LONG_STAT_TS_FORMAT_REFRESH_MILLIS,
	INTEGER_STAT_IN_MEMORY_PAST_UNITS,
	LONG_STAT_SLEEP_PER_TICK_MILLIS,
	
	LONG_STAT_RECALC_INDICATORS_FROM_MILLIS,
	LONG_STAT_RECALC_INDICATORS_TO_MILLIS,
	STRING_STAT_RECALC_INDICATORS_GRANULARITIES,
	STRING_STAT_RECALC_INDICATORS_MP,
	STRING_STAT_RECALC_INDICATORS_PRODUCTID,
	
	
	/*
	 * 
	 * Bots
	 */
	
	LONG_BOT_SLEEP_PER_FLUSH_MILLIS,
	LONG_BOT_TIMEOUT_SLEEP_PER_LOOP_MILLIS,
	LONG_SIMUL_ORDER_SLEEP_PER_FLUSH_MILLIS,
}
